# Generated by Django 3.1.1 on 2020-09-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_name', models.CharField(max_length=255)),
                ('columns', models.JSONField()),
                ('key_column', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_key', models.TextField()),
                ('type', models.TextField()),
                ('name', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('template_file', models.TextField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.spreadsheet')),
            ],
        ),
        migrations.CreateModel(
            name='TableOfContents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('json_file', models.TextField()),
                ('template_file', models.TextField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablesofcontents', to='core.spreadsheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiki_key', models.TextField()),
                ('group', models.TextField()),
                ('valid_ids', models.JSONField()),
                ('valid_columns', models.JSONField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.spreadsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.spreadsheet')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('object_id', models.TextField()),
                ('permissions_column', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.spreadsheet')),
            ],
        ),
        migrations.AddConstraint(
            model_name='row',
            constraint=models.UniqueConstraint(fields=('sheet', 'row_number'), name='unique_row_number'),
        ),
    ]
