# Generated by Django 3.1.2 on 2020-11-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.TextField(null=True),
        ),
    ]

