"""
Django settings for torque project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import config

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django_extensions",
    "torque",
    "torque.cache_rebuilder",
]

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

ROOT_URLCONF = "torque.urls"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": config.POSTGRES_DB_NAME,
        "USER": config.POSTGRES_DB_USER,
        "PASSWORD": config.POSTGRES_DB_PASSWORD,
        "HOST": "localhost",
    }
}

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_L10N = True
USE_TZ = True
MEDIA_ROOT = config.MEDIA_ROOT

TORQUE_COLLECTIONS_ALIAS = config.TORQUE_COLLECTIONS_ALIAS
TORQUE_DOCUMENTS_ALIAS = config.TORQUE_DOCUMENTS_ALIAS
TORQUE_ENABLED_JINJA_EXTENSIONS = config.TORQUE_ENABLED_JINJA_EXTENSIONS
TORQUE_FILTERS = config.TORQUE_FILTERS
TORQUE_CSV_PROCESSORS = config.TORQUE_CSV_PROCESSORS
