# Generated by Django 3.1.7 on 2021-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0002_auto_20210321_1604"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attachment",
            constraint=models.UniqueConstraint(
                fields=("sheet", "row", "name"), name="unique_attachment"
            ),
        ),
    ]
