# Generated by Django 3.1.7 on 2021-03-23 13:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0003_auto_20210321_1725"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchcacherow",
            name="data_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name="searchcacherow",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data_vector"], name="torque_search_data_ve_67ae25_gin"
            ),
        ),
    ]
