# Generated by Django 3.1.7 on 2021-03-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0005_auto_20210323_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetconfig",
            name="in_config",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sheetconfig",
            name="search_cache_sha",
            field=models.CharField(default="", max_length=255),
        ),
    ]
