# Generated by Django 3.1.7 on 2021-04-06 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0006_auto_20210323_1623"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celledit",
            name="config",
        ),
        migrations.AddField(
            model_name="celledit",
            name="sheet",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="torque.spreadsheet",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="celledit",
            name="wiki_key",
            field=models.TextField(null=True),
        ),
    ]
