# Generated by Django 3.1.7 on 2021-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0008_auto_20210406_1909"),
    ]

    operations = [
        migrations.AddField(
            model_name="sheetconfig",
            name="search_cache_dirty",
            field=models.BooleanField(default=False),
        ),
    ]
