# Generated by Django 3.1.7 on 2021-04-16 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0009_sheetconfig_search_cache_dirty"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableOfContentsCache",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dirty", models.BooleanField(default=True)),
                ("rendered_data", models.TextField()),
                (
                    "sheet_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cached_tocs",
                        to="torque.sheetconfig",
                    ),
                ),
                (
                    "toc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="torque.tableofcontents",
                    ),
                ),
            ],
        ),
    ]
