# Generated by Django 3.1.7 on 2021-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0010_tableofcontentscache"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="tableofcontentscache",
            constraint=models.UniqueConstraint(
                fields=("sheet_config", "toc"), name="unique_toc_cache"
            ),
        ),
    ]
