# Generated by Django 3.1.7 on 2021-04-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0011_auto_20210416_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchcacherow",
            name="dirty",
            field=models.BooleanField(default=False),
        ),
    ]
