# Generated by Django 3.2.5 on 2021-07-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0016_auto_20210721_1444"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="celledit",
            name="wiki_key",
        ),
        migrations.RemoveField(
            model_name="searchcacherow",
            name="wiki_key",
        ),
        migrations.RemoveField(
            model_name="sheetconfig",
            name="wiki_key",
        ),
        migrations.RemoveField(
            model_name="template",
            name="wiki_key",
        ),
    ]
