# Generated by Django 3.2.5 on 2021-07-21 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0017_auto_20210721_1621"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PermissionGroup",
        ),
    ]
