# Generated by Django 3.2.5 on 2021-07-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0018_delete_permissiongroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="wiki",
            name="password",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wiki",
            name="script_path",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wiki",
            name="server",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="wiki",
            name="username",
            field=models.TextField(null=True),
        ),
    ]
