# Generated by Django 3.2.7 on 2021-09-05 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0020_tableofcontents_raw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="column",
            name="type",
        ),
    ]
