# Generated by Django 3.2.7 on 2021-09-05 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0021_remove_column_type"),
    ]

    operations = [
        migrations.RenameModel("Cell", "Value"),
        migrations.RenameModel("CellEdit", "ValueEdit"),
        migrations.RenameField("Value", "original_value", "original"),
        migrations.RenameField("Value", "latest_value", "latest"),
        migrations.RenameField("ValueEdit", "value", "updated"),
        migrations.RenameField("ValueEdit", "cell", "value"),
    ]
