# Generated by Django 3.2.7 on 2021-09-05 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0022_auto_20210905_1430"),
    ]

    operations = [
        migrations.AlterField(
            model_name="value",
            name="column",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="torque.column",
            ),
        ),
        migrations.AlterField(
            model_name="value",
            name="row",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="torque.row",
            ),
        ),
    ]
