# Generated by Django 3.2.7 on 2021-09-05 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0023_auto_20210905_1454"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spreadsheet",
            old_name="key_column",
            new_name="key_field",
        ),
        migrations.RenameField(
            model_name="value",
            old_name="column",
            new_name="field",
        ),
        migrations.RenameField(
            model_name="attachment",
            old_name="permissions_column",
            new_name="permissions_field",
        ),
        migrations.RenameModel("Column", "Field"),
    ]
