# Generated by Django 3.2.7 on 2021-09-05 16:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0025_auto_20210905_1624"),
    ]

    operations = [
        migrations.RenameModel("Row", "Document"),
        migrations.RenameModel("SearchCacheRow", "SearchCacheDocument"),
        migrations.RenameField(
            model_name="value",
            old_name="row",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="attachment",
            old_name="row",
            new_name="document",
        ),
        migrations.RenameField(
            model_name="searchcachedocument",
            old_name="row",
            new_name="document",
        ),
    ]
