# Generated by Django 3.2.7 on 2021-09-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0027_auto_20210905_1642"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SheetConfig",
            new_name="WikiConfig",
        ),
        migrations.RemoveConstraint(
            model_name="tableofcontentscache",
            name="unique_toc_cache",
        ),
        migrations.RenameField(
            model_name="searchcachedocument",
            old_name="sheet_config",
            new_name="wiki_config",
        ),
        migrations.RenameField(
            model_name="tableofcontentscache",
            old_name="sheet_config",
            new_name="wiki_config",
        ),
        migrations.RenameField(
            model_name="document",
            old_name="sheet_config",
            new_name="wiki_config",
        ),
        migrations.RenameField(
            model_name="field",
            old_name="sheet_config",
            new_name="wiki_config",
        ),
        migrations.AddConstraint(
            model_name="tableofcontentscache",
            constraint=models.UniqueConstraint(
                fields=("wiki_config", "toc"), name="unique_toc_cache"
            ),
        ),
    ]
