# Generated by Django 3.2.7 on 2021-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0029_auto_20210905_1716"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="template",
            name="unique_template",
        ),
        migrations.AddConstraint(
            model_name="template",
            constraint=models.UniqueConstraint(
                fields=("collection", "wiki", "type", "name"), name="unique_template"
            ),
        ),
    ]
