# Generated by Django 3.2.7 on 2022-02-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0033_csvspecification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wikiconfig",
            old_name="search_cache_dirty",
            new_name="cache_dirty",
        ),
        migrations.CreateModel(
            name="TemplateCacheDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rendered_text", models.TextField(null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="torque.document"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="torque.template"
                    ),
                ),
                (
                    "wiki_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="torque.wikiconfig",
                    ),
                ),
            ],
        ),
    ]
