# Generated by Django 3.2.7 on 2022-02-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("torque", "0034_auto_20220209_1209"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="in_config",
            field=models.BooleanField(default=False),
        ),
    ]
